version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: korean_study_hub_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sa123
      MYSQL_DATABASE: korean_study_hub
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
