"""English copy for the Practice Use Case specification document.

The architecture generator keeps its original diagram model unchanged. This
module supplies the reader-facing English wording used by the DOCX artifact.
"""

from __future__ import annotations


ACTOR_NAMES = {
    "After-commit listener": "After-commit listener",
    "Bộ giải mã Excel": "Excel decoder",
    "Cơ sở dữ liệu": "Database",
    "Cộng tác viên": "Collaborator",
    "Dịch vụ chấm điểm": "Scoring service",
    "Dịch vụ phân quyền": "Authorization service",
    "Explanation read service": "Explanation read service",
    "Giảng viên": "Lecturer",
    "Hàng đợi explanation": "Explanation queue",
    "Kho PDF": "PDF storage",
    "Kho audio riêng tư": "Private audio storage",
    "Kho media riêng tư": "Private media storage",
    "Kho tài liệu": "Document storage",
    "Người học": "Student",
    "Người vận hành": "Operator",
    "Người đánh giá": "Reviewer",
    "Nhà cung cấp AI": "AI provider",
    "Nhà cung cấp phiên âm/AI": "Transcription and AI provider",
    "Quản trị viên": "Administrator",
    "Result assembler": "Result assembler",
    "Result presenters": "Result presenters",
    "Result services": "Result services",
    "Retry services": "Retry services",
    "Retry/re-evaluate services": "Retry and re-evaluation services",
    "Speaking evidence presenter": "Speaking evidence presenter",
    "Thiết bị trình duyệt": "Browser device",
    "Thiết bị âm thanh/micro": "Audio device and microphone",
    "Worker": "Worker",
    "Writing evidence presenter": "Writing evidence presenter",
}


CAPABILITY_COPY = {
    "CAT": {
        "name": "Catalog, access and attempt entry",
        "purpose": "Help students find an authorized test, understand its structure, and start or resume an attempt locked to an immutable version.",
    },
    "AUT": {
        "name": "Manual authoring, publishing and revision",
        "purpose": "Let authorized lecturers build drafts, publish immutable test versions, and create controlled revisions without changing historical attempts.",
    },
    "XLS": {
        "name": "Excel template, preview and import",
        "purpose": "Give lecturers a rules-aware spreadsheet workflow that validates content and media before importing a normal editable draft.",
    },
    "PDF": {
        "name": "PDF workspace and AI-assisted draft import",
        "purpose": "Let lecturers select visible PDF regions, review the exact AI payload, and import only validated generated questions.",
    },
    "PLY": {
        "name": "Skill-native player and attempt lifecycle",
        "purpose": "Deliver Reading, Listening, Writing and Speaking players with safe preflight, autosave, resume, timeout and submission behavior.",
    },
    "RLE": {
        "name": "Reading and Listening explanation lifecycle",
        "purpose": "Prepare reusable immutable explanations after publication and show them with a separate student-answer overlay.",
    },
    "WRT": {
        "name": "Korean Writing AI evaluation and result evidence",
        "purpose": "Evaluate submitted Korean writing with the approved rubric and present traceable feedback without inventing scores.",
    },
    "SPK": {
        "name": "Speaking media, transcription and evaluation",
        "purpose": "Protect student recordings, transcribe and evaluate them against Korean speaking criteria, and present holistic evidence.",
    },
    "RES": {
        "name": "Result overview and evidence detail",
        "purpose": "Present a skill-appropriate overview and a clearly layered detail view for scores, answers, explanations and AI evidence.",
    },
    "PRG": {
        "name": "Progress, drill-down and recovery",
        "purpose": "Show real bounded learning history and provide authorized drill-down or recovery actions for incomplete evaluations.",
    },
}


DOCUMENT_GROUPS = [
    {
        "code": "MGT",
        "name": "Practice Test Management",
        "purpose": "Create tests manually or from Excel and PDF, publish validated immutable versions, and manage controlled revisions.",
        "capabilities": ["AUT", "XLS", "PDF"],
    },
    {
        "code": "ATT",
        "name": "Skill-based Attempt Lifecycle",
        "purpose": "Let students browse tests and safely start, check devices, resume, discard, complete, time out, or submit a skill-specific attempt.",
        "capabilities": ["CAT", "PLY"],
    },
    {
        "code": "RSL",
        "name": "Versioned Results and Evidence",
        "purpose": "Prepare and present version-locked Reading, Listening, Writing and Speaking results with clearly separated evidence layers.",
        "capabilities": ["RLE", "WRT", "SPK", "RES"],
    },
    {
        "code": "PRG",
        "name": "Practice Progress Management",
        "purpose": "Show real bounded Practice history, consistent progress summaries, drill-down, and authorized recovery paths.",
        "capabilities": ["PRG"],
    },
]


BUSINESS_RULES = {
    "BR-01": "Only an authenticated user with an active account can access protected Practice functions.",
    "BR-02": "Every protected action must verify both the user's role and access to the requested Practice resource.",
    "BR-03": "A Student can access only published Practice content and attempts that the Student is authorized to use.",
    "BR-04": "Only the owning Lecturer or an authorized collaborator can create, edit, import, publish or revise a Practice draft.",
    "BR-05": "Every attempt and result remains tied to exactly one immutable published version, including historical review.",
    "BR-06": "A read-only page cannot create an attempt, start a timer, change stored evidence or call an AI provider.",
    "BR-07": "An external provider failure cannot create fabricated questions, transcripts, explanations, scores or feedback.",
    "BR-08": "Retry and re-evaluation require authorization, are safe to repeat, preserve accepted evidence and create an audit record.",
    "BR-09": "A state-changing command must be atomic and safe to repeat without creating duplicate outcomes.",
    "BR-10": "Uploaded documents and media must satisfy file, size, duration, ownership and retention policies.",
    "BR-11": "An older editor revision cannot overwrite newer draft content.",
    "BR-12": "A draft must pass the current content, scoring and media checks before publication.",
    "BR-13": "Publication is all-or-nothing; required immutable records are committed together before after-commit work is queued.",
    "BR-14": "A published version is never edited in place; later changes begin in a new draft revision.",
    "BR-15": "Revision, restore and collaborator changes require permission and leave an audit record.",
    "BR-16": "The downloadable Excel template must match the current Practice rules and allowed question types.",
    "BR-17": "Template examples and media guidance must be understandable without knowledge of internal database fields.",
    "BR-18": "Excel and PDF previews are read-only and must identify each problem or selected region clearly.",
    "BR-19": "The server revalidates every import and commits only one complete canonical editable draft.",
    "BR-20": "A PDF import session belongs to one Lecturer and target draft, has bounded resources and expires according to policy.",
    "BR-21": "Every PDF region remains traceable to its source page and coordinates; changing it invalidates older crops and previews.",
    "BR-22": "The AI provider receives only Lecturer-approved regions, and generated questions must pass normal draft validation.",
    "BR-23": "A failed or invalid AI response cannot partially import a draft, and manual fallback keeps the approved source evidence.",
    "BR-24": "The catalog uses bounded pagination and shows only published sets that the Student is authorized to use.",
    "BR-25": "Test details use the current published version; an older version is visible only through its authorized attempt.",
    "BR-26": "An active attempt must be resumed or explicitly discarded and cannot be silently replaced.",
    "BR-27": "Listening and Speaking device checks do not consume attempt time, and the sound check succeeds when sample audio starts playing.",
    "BR-28": "The server deadline is authoritative; the browser timer only displays that deadline.",
    "BR-29": "Autosave and resume preserve the latest accepted answers, and stale updates cannot overwrite newer answers.",
    "BR-30": "Submission and timeout finalization are atomic, repeat-safe and use the exact version locked to the attempt.",
    "BR-31": "Official answers remain hidden until the attempt and configured review conditions allow them to be shown.",
    "BR-32": "Reading and Listening explanations are prepared after publication, independently of attempts, and tied to an immutable content fingerprint.",
    "BR-33": "An approved explanation is reused by fingerprint, while failed preparation remains honestly failed or retryable.",
    "BR-34": "Opening a result or explanation is read-only and never starts provider work.",
    "BR-35": "A shared explanation is stored separately from the Student's answer, correctness and score overlay.",
    "BR-36": "Writing questions 51 through 54 remain essay responses evaluated with the approved Korean task weights and rubric.",
    "BR-37": "Writing evidence is reused only for a matching evaluation fingerprint; re-evaluation preserves earlier evidence and is audited.",
    "BR-38": "The four Writing views cannot rename the Korean criteria and must distinguish official score, AI evidence and improvement advice.",
    "BR-39": "Speaking recordings are private, policy-compliant and available only to the owning Student or an authorized reviewer.",
    "BR-40": "Speaking evaluation uses six approved Korean criteria and produces one holistic attempt-level assessment.",
    "BR-41": "Speaking detail may show recordings, transcripts and question context but cannot invent per-question scores.",
    "BR-42": "Result Overview is skill-specific, version-locked and cannot combine scores that use incompatible scales.",
    "BR-43": "Result Detail keeps Student answers, official answers, teacher explanations and AI evidence as separate authorized layers.",
    "BR-44": "Pending, failed and unavailable result states must be shown honestly without invented percentages or feedback.",
    "BR-45": "Practice progress uses only persisted authorized attempts, and history queries are bounded by pagination and date limits.",
    "BR-46": "Progress summaries and history use the same filters and keep incompatible scoring scales separate.",
    "BR-47": "A progress trend states its sample size and recency and avoids strong claims when evidence is limited.",
    "BR-48": "A progress deep link keeps the exact attempt identity and offers only actions valid for that attempt.",
    "BR-49": "A progress failure shows a recoverable Student-safe state; legacy test data is marked for Phase 15 cleanup.",
}


SYSTEM_MESSAGES = {
    "MSG-AUTH-01": "Your session has expired. Please sign in again.",
    "MSG-AUTH-02": "You are not allowed to perform this action.",
    "MSG-MGT-01": "Draft saved.",
    "MSG-MGT-02": "A newer draft revision exists. Reload before saving again.",
    "MSG-MGT-03": "Resolve the listed problems before publishing.",
    "MSG-MGT-04": "The Practice version was published successfully.",
    "MSG-MGT-05": "A new draft revision was created.",
    "MSG-MGT-06": "The Excel template is ready.",
    "MSG-MGT-07": "A template cannot be generated for the current configuration.",
    "MSG-MGT-08": "Review the identified workbook problems before importing.",
    "MSG-MGT-09": "The workbook was imported as an editable draft.",
    "MSG-MGT-10": "The PDF cannot be read.",
    "MSG-MGT-11": "The PDF import session has expired.",
    "MSG-MGT-12": "The selected PDF region is invalid.",
    "MSG-MGT-13": "The crop or payload preview is outdated. Generate it again.",
    "MSG-MGT-14": "AI could not process the approved PDF evidence.",
    "MSG-MGT-15": "The generated content must be corrected before import.",
    "MSG-ATT-01": "No matching Practice set was found.",
    "MSG-ATT-02": "This Practice test is unavailable or outside your access scope.",
    "MSG-ATT-03": "You already have an unfinished attempt.",
    "MSG-ATT-04": "The test version changed. Reload the test details.",
    "MSG-ATT-05": "Device check completed. You can start the attempt.",
    "MSG-ATT-06": "Sample audio could not be played. Check the device and try again.",
    "MSG-ATT-07": "Answers saved.",
    "MSG-ATT-08": "Answers could not be saved. Retry before leaving the page.",
    "MSG-ATT-09": "Attempt submitted successfully.",
    "MSG-ATT-10": "Time expired and the latest accepted answers were submitted.",
    "MSG-RES-01": "Explanation is available.",
    "MSG-RES-02": "Explanation is still processing or could not be prepared.",
    "MSG-RES-03": "Writing evaluation completed.",
    "MSG-RES-04": "Writing evaluation is unavailable; no score was invented.",
    "MSG-RES-05": "Speaking recording saved.",
    "MSG-RES-06": "The recording cannot be used. Record the answer again.",
    "MSG-RES-07": "Speaking evaluation completed.",
    "MSG-RES-08": "Speaking evaluation is pending or unavailable.",
    "MSG-RES-09": "Result Overview is ready.",
    "MSG-RES-10": "Part of this result is still being evaluated.",
    "MSG-RES-11": "This evidence is unavailable for the selected attempt version.",
    "MSG-RES-12": "Recovery was requested; accepted evidence remains unchanged.",
    "MSG-PRG-01": "No Practice history is available yet.",
    "MSG-PRG-02": "Some progress data could not be loaded. Please retry.",
    "MSG-PRG-03": "No attempts match these filters.",
    "MSG-PRG-04": "More comparable attempts are needed before showing a trend.",
    "MSG-PRG-05": "This historical result needs support before it can be recovered.",
}


def case(
    title: str,
    description: str,
    preconditions: list[str],
    success: list[str],
    failure: list[str],
    steps: list[str],
    alternatives: list[str],
    rule_ids: list[str],
    message_ids: list[str],
) -> dict[str, object]:
    return {
        "title": title,
        "description": description,
        "preconditions": preconditions,
        "success": success,
        "failure": failure,
        "steps": steps,
        "alternatives": alternatives,
        "rule_ids": rule_ids,
        "message_ids": message_ids,
    }


USE_CASE_COPY = {
    "UC-CAT-01": case(
        "Browse and filter the Practice catalog",
        "Shows a bounded catalog of published Practice sets that the student is allowed to access, with stable filters and pagination.",
        ["The student is signed in with an active account.", "The Practice catalog route is available."],
        ["An authorized catalog page is displayed.", "Filters and page state remain represented in the URL."],
        ["No draft, locked or out-of-scope set is disclosed.", "No attempt is created by this read operation."],
        ["The student opens /practice.", "The system validates the student session.", "The student chooses a skill, scope or keyword filter.", "The system normalizes the filter values and applies query limits.", "The system loads only authorized published sets.", "The page shows results, pagination or a truthful empty state."],
        ["A1 - Invalid filter: use a safe default and keep the page usable.", "A2 - No match: show an empty state without fabricated sample data."],
        ["BR-01", "BR-03", "BR-24"],
        ["MSG-ATT-01", "MSG-AUTH-01"],
    ),
    "UC-CAT-02": case(
        "View Practice set and test details",
        "Lets the student review the set, test, skill, duration and device requirements before starting an attempt.",
        ["The set and test exist.", "The student can read the current published version."],
        ["The test structure and available modes are displayed.", "The correct start or resume action is shown."],
        ["Unauthorized historical content is not disclosed.", "Viewing details does not start the timer."],
        ["The student selects a set from the catalog.", "The system checks access to the published graph.", "The system loads the bounded test and skill structure.", "The student selects a test.", "The system determines duration, mode and device requirements.", "The page presents the appropriate start or resume action."],
        ["A1 - Missing or forbidden test: show a safe not-found or access-denied page.", "A2 - Disabled skill: disable the start action and explain why."],
        ["BR-03", "BR-05", "BR-06", "BR-25"],
        ["MSG-AUTH-02", "MSG-ATT-02"],
    ),
    "UC-CAT-03": case(
        "Start, resume or discard an attempt",
        "Creates a new version-locked attempt or resumes an existing one, then routes the student to the correct preflight or player.",
        ["The student is authorized to take the test.", "The test has a valid published version."],
        ["A version-locked attempt is created or reused.", "The student is routed to the correct preflight or player."],
        ["Two conflicting active attempts are not created.", "An existing attempt is discarded only after confirmation."],
        ["The student chooses Start or Resume.", "The system checks access and searches for an active attempt.", "For a new attempt, the system locks the current published version in one transaction.", "The system creates the immutable delivery snapshot.", "The system selects the skill-specific preflight or player route.", "The browser redirects to that route."],
        ["A1 - Active attempt found: offer Resume or Discard instead of overwriting it.", "A2 - Published version changed during the request: stop safely and ask the student to reload."],
        ["BR-02", "BR-05", "BR-09", "BR-26"],
        ["MSG-ATT-03", "MSG-ATT-04"],
    ),
    "UC-AUT-01": case(
        "Create, edit and autosave a Practice draft",
        "Lets a lecturer or authorized collaborator build a set, tests, skills and questions while preserving the latest valid draft revision.",
        ["The user is an authorized lecturer or collaborator.", "The target set is editable and not an immutable published version."],
        ["The latest valid draft is stored.", "The editor receives the accepted revision number."],
        ["Unauthorized or stale changes do not overwrite the draft.", "A validation problem remains visible to the editor."],
        ["The user opens a new or existing draft.", "The system checks ownership and collaborator permissions.", "The user edits structure, content, scoring or media references.", "The browser sends an autosave request with its revision number.", "The server validates the draft contract and rejects stale revisions.", "The server stores the accepted revision and returns save status."],
        ["A1 - Stale revision: keep the newer server copy and ask the user to refresh or merge.", "A2 - Invalid field: keep the editor open and identify the affected field."],
        ["BR-04", "BR-11"],
        ["MSG-MGT-01", "MSG-MGT-02", "MSG-AUTH-02"],
    ),
    "UC-AUT-02": case(
        "Validate and publish an immutable version",
        "Validates the complete draft graph and publishes one immutable version that can safely support future attempts and explanations.",
        ["The lecturer owns the editable draft.", "The draft contains at least one valid test and question."],
        ["One immutable published version is committed.", "Post-publication explanation preparation may be queued after commit."],
        ["A failed validation or transaction leaves no partial published graph.", "The editable draft remains available for correction."],
        ["The lecturer chooses Publish.", "The system checks ownership and the current draft revision.", "The system validates content, scoring and media references.", "The system creates the versioned graph in one transaction.", "The transaction marks the new version as published.", "After commit, the system emits the preparation event and confirms success."],
        ["A1 - Validation fails: show grouped actionable errors and do not publish.", "A2 - Commit fails: roll back the complete version and keep the draft unchanged."],
        ["BR-04", "BR-12", "BR-13"],
        ["MSG-MGT-03", "MSG-MGT-04"],
    ),
    "UC-AUT-03": case(
        "Create a revision and manage collaborators",
        "Creates a new editable revision from approved content and controls who may review or change that revision.",
        ["A published version or editable draft exists.", "The user has permission to revise or manage collaborators."],
        ["A new draft revision is created without changing historical versions.", "Collaborator access matches the recorded permissions."],
        ["A protected published graph remains unchanged.", "Unauthorized restore or collaborator changes are denied and audited."],
        ["The owner opens version history or collaborator settings.", "The system verifies the requested action and target version.", "For a revision, the system copies approved content into a new draft identity.", "For collaboration, the owner grants or removes an allowed role.", "The system stores the action with its actor and reason.", "The page shows the new revision or collaborator state."],
        ["A1 - Protected version mutation requested: reject it and direct the user to Create revision.", "A2 - Collaborator no longer eligible: deny the change and preserve current ownership."],
        ["BR-04", "BR-14", "BR-15"],
        ["MSG-MGT-05", "MSG-AUTH-02"],
    ),
    "UC-XLS-01": case(
        "Download a rules-aware Excel template",
        "Builds an Excel template from the current Practice rules so lecturers see only valid fields, question types and examples.",
        ["The lecturer is signed in and can author Practice content.", "The target configuration can be resolved."],
        ["A current template is downloaded.", "The workbook contains readable instructions and representative example rows."],
        ["A template is not generated from missing or inconsistent rules.", "Internal database terminology is not exposed as teaching guidance."],
        ["The lecturer chooses Download template.", "The system resolves current skill and question rules.", "The system builds the workbook sheets and validation lists.", "The system adds understandable examples and media naming guidance.", "The system records the template contract version.", "The browser downloads the generated workbook."],
        ["A1 - Configuration unavailable: stop and show a supportable error.", "A2 - Optional feature disabled: omit its columns and explain the current boundary in the instructions sheet."],
        ["BR-04", "BR-16", "BR-17"],
        ["MSG-MGT-06", "MSG-MGT-07"],
    ),
    "UC-XLS-02": case(
        "Preview a workbook and resolve validation issues",
        "Parses an uploaded workbook into a read-only preview with row-level problems, media matches and the draft structure that would be imported.",
        ["The lecturer can edit the target draft.", "The uploaded file uses a supported workbook format."],
        ["A read-only preview and validation summary are displayed.", "Each problem points to a sheet, row and field."],
        ["Preview does not alter the target draft or assets.", "Unauthorized or missing media is not silently accepted."],
        ["The lecturer uploads a workbook and optional media package.", "The system checks file type, size and template contract version.", "The decoder parses rows into the canonical preview model.", "The system validates fields, grouping, scoring and media references.", "The system groups errors and warnings by location.", "The page displays importable rows and corrections still required."],
        ["A1 - Workbook cannot be parsed: show the failing sheet or format reason.", "A2 - Media reference is ambiguous: require the lecturer to choose or rename the asset."],
        ["BR-04", "BR-10", "BR-18"],
        ["MSG-MGT-08"],
    ),
    "UC-XLS-03": case(
        "Import a workbook as a standard editable draft",
        "Revalidates the previewed workbook and imports its complete canonical structure into the normal authoring workflow.",
        ["The preview has no blocking errors.", "The lecturer still has edit permission on the target draft."],
        ["One complete editable draft revision is stored.", "The imported content can be reviewed and published through normal authoring."],
        ["A failed import leaves the previous draft unchanged.", "No partial question or asset binding remains."],
        ["The lecturer reviews the preview and chooses Import.", "The server reloads the upload and rechecks permission.", "The server revalidates rows and media against current rules.", "The server assembles the canonical draft snapshot.", "The system stores the complete revision in one transaction.", "The browser opens the normal draft editor with an import summary."],
        ["A1 - Rules changed after preview: stop and request a new preview.", "A2 - Transaction fails: roll back all imported content and keep the prior draft."],
        ["BR-04", "BR-09", "BR-19"],
        ["MSG-MGT-09", "MSG-MGT-08"],
    ),
    "UC-PDF-01": case(
        "Upload a PDF and create an import session",
        "Creates a private, bounded workspace where a lecturer can inspect PDF pages before selecting content for question generation.",
        ["The lecturer can edit the target Practice draft.", "The PDF satisfies configured type, size and page limits."],
        ["A private import session is created.", "Page thumbnails and extraction status are displayed."],
        ["Rejected files are not retained as usable session content.", "Another user cannot open the session."],
        ["The lecturer opens the PDF import workspace.", "The lecturer selects a PDF and target draft.", "The system validates authorization and file limits.", "The system stores the source under a private session identity.", "The page extractor prepares bounded page previews.", "The workspace displays pages and session expiry information."],
        ["A1 - Unsupported or oversized PDF: reject it with the applicable limit.", "A2 - A page cannot be extracted: mark that page unavailable while keeping the session safe."],
        ["BR-04", "BR-10", "BR-20"],
        ["MSG-MGT-10", "MSG-MGT-11"],
    ),
    "UC-PDF-02": case(
        "Select, crop and preview PDF regions",
        "Lets the lecturer mark question, option, image or context regions and inspect the exact cropped payload before any AI request.",
        ["The lecturer owns an active PDF import session.", "The selected source page is available."],
        ["Region coordinates and crop previews are stored for the session.", "The assembled AI payload is visible before generation."],
        ["A stale crop is not reused after a region changes.", "Coordinates outside the source page are rejected."],
        ["The lecturer selects a source page.", "The lecturer draws and labels one or more regions.", "The system validates page bounds and region type.", "The crop service creates visible previews from the current coordinates.", "The payload service assembles approved text and images.", "The workspace displays the exact payload and any missing requirements."],
        ["A1 - Region is invalid or empty: keep it editable and explain the required correction.", "A2 - Region changes after preview: invalidate the old crop and rebuild the payload."],
        ["BR-04", "BR-18", "BR-21"],
        ["MSG-MGT-12", "MSG-MGT-13"],
    ),
    "UC-PDF-03": case(
        "Generate questions with AI and import a validated draft",
        "Sends only the reviewed PDF payload to the AI provider, validates the response, and imports accepted questions through the normal draft contract.",
        ["The lecturer approved the current payload preview.", "All required regions and provider settings are available."],
        ["Valid generated questions are shown for review.", "Confirmed questions are imported as one editable draft revision."],
        ["Invalid or failed AI output creates no partial draft.", "The lecturer can retry or continue with manual authoring."],
        ["The lecturer chooses Generate from the reviewed payload.", "The orchestrator confirms session ownership and payload freshness.", "The AI provider receives only the approved bounded content.", "The response is normalized and validated against Practice rules.", "The lecturer reviews the generated draft questions.", "On confirmation, the system imports all accepted content transactionally."],
        ["A1 - Provider fails or times out: keep the workspace and offer a safe retry.", "A2 - Response violates the draft contract: show validation problems and do not import it."],
        ["BR-04", "BR-07", "BR-22", "BR-23"],
        ["MSG-MGT-14", "MSG-MGT-15"],
    ),
    "UC-PLY-01": case(
        "Complete device checks and enter the correct player",
        "Checks Listening audio or Speaking microphone readiness before routing the student to the immutable skill-specific player.",
        ["The student can start or resume the test.", "A valid immutable delivery route is available."],
        ["The required device check is confirmed.", "The student enters the correct player without losing test time."],
        ["A failed check keeps the student outside the timed player.", "The system does not require sample audio to play to completion."],
        ["The student opens the preflight page.", "The system resolves the locked attempt delivery and required device checks.", "For Listening, the student starts sample audio; for Speaking, the student grants microphone access and records a sample.", "The page confirms readiness when playback or capture actually starts.", "The student confirms that the device works.", "The system redirects to the correct skill player."],
        ["A1 - Browser blocks playback or microphone access: show device-specific recovery guidance.", "A2 - Delivery cannot be resolved: keep the timer stopped and return a student-safe error."],
        ["BR-03", "BR-06", "BR-27"],
        ["MSG-ATT-05", "MSG-ATT-06"],
    ),
    "UC-PLY-02": case(
        "Answer, autosave, navigate and resume",
        "Delivers the immutable question snapshot, stores accepted answers safely, and restores the latest attempt state after navigation or reconnect.",
        ["The attempt is active and locked to a published version.", "The server deadline has not passed."],
        ["Accepted answers are persisted with the attempt.", "Resume restores the current question, answers and remaining server time."],
        ["Stale updates do not overwrite newer answers.", "Official answers are not disclosed while the attempt is active."],
        ["The player loads the immutable attempt delivery.", "The student answers or records the current question.", "The browser autosaves with the current answer revision.", "The server checks ownership, deadline and revision before accepting it.", "The student navigates between allowed questions or sections.", "After reconnect or resume, the server returns the latest accepted state and deadline."],
        ["A1 - Autosave is stale: return the newer server state without overwriting it.", "A2 - Network interruption: keep a visible unsaved state and retry safely after reconnect."],
        ["BR-05", "BR-28", "BR-29"],
        ["MSG-ATT-07", "MSG-ATT-08"],
    ),
    "UC-PLY-03": case(
        "Submit or finalize an attempt safely",
        "Finalizes an active attempt once, using the locked version for objective scoring and durable follow-up evaluation work.",
        ["The attempt belongs to the student and is active.", "The immutable version and accepted answers are available."],
        ["The attempt reaches one final status.", "Objective scores and required follow-up tasks are persisted consistently."],
        ["A duplicate request cannot create a second result.", "A failed transaction leaves the attempt recoverable rather than partly submitted."],
        ["The student chooses Submit, or the server deadline is reached.", "The system locks the active attempt and reloads accepted answers.", "The scoring engine evaluates objective questions against the locked version.", "The system records submission time, final status and objective results in one transaction.", "After commit, required explanation or AI evaluation work may be queued.", "The student is redirected to the honest result state."],
        ["A1 - Duplicate submit: return the existing final result without scoring again.", "A2 - Transaction fails: roll back and keep a recoverable submission state."],
        ["BR-05", "BR-09", "BR-30", "BR-31"],
        ["MSG-ATT-09", "MSG-ATT-10"],
    ),
    "UC-RLE-01": case(
        "Queue explanation preparation after publishing",
        "Creates durable Reading and Listening explanation work only after the immutable published version has committed successfully.",
        ["A version was published successfully.", "Eligible Reading or Listening questions exist in that version."],
        ["Eligible questions receive durable preparation tasks.", "Each task records the immutable content fingerprint and version binding."],
        ["A rolled-back publication creates no explanation task.", "Student attempt data is not included in the shared artifact request."],
        ["The publication transaction commits the immutable version.", "The after-commit listener receives the published version event.", "The preparation service loads eligible immutable questions.", "The fingerprint builder includes approved prompt, options, answer and supporting material.", "The system creates or reuses one durable task per required artifact.", "The worker queue receives the ready tasks."],
        ["A1 - Question is not eligible: record no task for that question.", "A2 - Equivalent task already exists: reuse it instead of creating a duplicate."],
        ["BR-12", "BR-13", "BR-32"],
        ["MSG-RES-01", "MSG-RES-02"],
    ),
    "UC-RLE-02": case(
        "Generate, reuse and retry explanation artifacts",
        "Processes durable tasks, reuses an approved matching artifact when possible, and records provider failures for controlled retry.",
        ["A durable explanation task is ready or retryable.", "Its immutable question and supporting materials are still available."],
        ["An approved artifact is bound to the immutable question version.", "The task reaches a truthful completed, failed or retryable state."],
        ["Provider failure does not create explanation text.", "A retry cannot bind an artifact built from different content."],
        ["The worker claims a ready task.", "The processor checks for an approved artifact with the same fingerprint.", "If none exists, the processor sends the bounded immutable content to the provider.", "The response is normalized and validated.", "The system stores the artifact and version binding transactionally.", "The task records completion or a classified retryable failure."],
        ["A1 - Matching approved artifact exists: bind and complete without a provider call.", "A2 - Provider or validation fails: record the failure and apply the retry policy."],
        ["BR-07", "BR-08", "BR-33"],
        ["MSG-RES-01", "MSG-RES-02"],
    ),
    "UC-RLE-03": case(
        "Read an explanation with a student-specific answer overlay",
        "Loads an approved immutable explanation and combines it at presentation time with the authorized student answer and correctness data.",
        ["The attempt is finalized and visible to the student.", "The requested question belongs to the attempt's locked version."],
        ["The result shows the shared explanation and student overlay as separate layers.", "No generation or mutation occurs during the read."],
        ["An unrelated historical artifact is not exposed.", "Missing explanation remains an honest unavailable state."],
        ["The student opens Reading or Listening result detail.", "The system authorizes the attempt and locked question version.", "The read service loads the approved version binding and shared artifact.", "The result assembler loads the student answer, official answer and correctness.", "The presenter labels each evidence layer clearly.", "The page renders the explanation or an honest unavailable state."],
        ["A1 - Artifact is pending or failed: show status and an authorized recovery path when allowed.", "A2 - Version binding does not match: deny the artifact rather than falling back to current content."],
        ["BR-03", "BR-34", "BR-35", "BR-43"],
        ["MSG-RES-01", "MSG-RES-02", "MSG-RES-11"],
    ),
    "UC-WRT-01": case(
        "Evaluate a submitted Korean writing response",
        "Evaluates a finalized essay response against the approved Korean Writing rubric, task weight and immutable question context.",
        ["The Writing attempt is finalized.", "The submitted essay and locked question version are available."],
        ["A validated score and criterion evidence are stored.", "The evaluation remains traceable to the exact answer and rubric fingerprint."],
        ["Invalid provider output produces no score.", "The student sees a pending or failed state instead of fabricated feedback."],
        ["The system identifies a Writing response that requires evaluation.", "The cache service builds the answer, rubric and question fingerprint.", "If no valid match exists, the provider receives the bounded Korean evaluation request.", "The normalizer validates score ranges, criterion evidence and task weight.", "The system stores the accepted evaluation and provenance.", "The result presenter exposes the new truthful state."],
        ["A1 - Valid matching evaluation exists: reuse it without another provider call.", "A2 - Provider or normalization fails: record failure and keep the score unavailable."],
        ["BR-07", "BR-36"],
        ["MSG-RES-03", "MSG-RES-04"],
    ),
    "UC-WRT-02": case(
        "Reuse or re-evaluate stored Writing feedback",
        "Reuses matching stored feedback by default and allows an authorized reviewer to request a traceable re-evaluation when needed.",
        ["A submitted Writing response and evaluation history exist.", "The requester can view the attempt; re-evaluation requires reviewer permission."],
        ["Matching feedback is reused or a new evaluation attempt is recorded.", "Earlier evidence remains available for audit."],
        ["An unauthorized request does not call the provider.", "A failed re-evaluation does not erase the prior valid result."],
        ["The result service computes the current evaluation fingerprint.", "The reuse policy checks stored evaluations for an exact valid match.", "For a student read, the matching evaluation is returned.", "For an authorized re-evaluation, the reviewer supplies a reason.", "The system creates a new evaluation attempt and preserves earlier evidence.", "The result shows the latest accepted evaluation and its provenance."],
        ["A1 - Fingerprint differs: do not reuse stale feedback; request a new evaluation.", "A2 - Re-evaluation fails: retain the earlier valid evaluation and show the failed attempt separately."],
        ["BR-07", "BR-08", "BR-37"],
        ["MSG-RES-03", "MSG-RES-04"],
    ),
    "UC-WRT-03": case(
        "Review Korean Writing criteria through four student-friendly views",
        "Presents task achievement, organization, vocabulary and grammar evidence in a clearer interactive layout while preserving the official Korean rubric.",
        ["A validated Writing evaluation is available.", "Phase 13E evidence presentation has been implemented."],
        ["The student can move among four criterion views.", "Official score, evidence and improvement advice remain clearly distinguished."],
        ["Missing evidence is not replaced with generic praise or invented metrics.", "The presentation does not change the stored evaluation."],
        ["The student opens Writing Result Detail.", "The detail assembler loads the immutable response and accepted evaluation.", "The presenter maps approved Korean criteria into four student-friendly views.", "The student selects a criterion tab.", "The page shows score descriptors, supporting evidence and advice for that criterion.", "The student can return to the overview without triggering evaluation."],
        ["A1 - Criterion evidence is absent: label it unavailable and keep the official score unchanged.", "A2 - Historical feedback uses an older shape: adapt it through the compatibility reader and label any unavailable field."],
        ["BR-34", "BR-38", "BR-43"],
        ["MSG-RES-03", "MSG-RES-11"],
    ),
    "UC-SPK-01": case(
        "Manage private attempt recordings",
        "Stores, validates and serves Speaking recordings under attempt ownership and reviewer authorization rules.",
        ["The student owns an active or retained Speaking attempt.", "The browser supplies a supported recording format."],
        ["Valid recordings are stored under private attempt-scoped identities.", "Authorized playback supports normal seeking and resume behavior."],
        ["Unauthorized or invalid media is rejected.", "A removed or expired recording is not served."],
        ["The Speaking player records an answer.", "The browser uploads the media with attempt and question identity.", "The service checks ownership, attempt state, file type, size and duration.", "The audio preparation service normalizes accepted media when required.", "Private storage records the media reference and lifecycle metadata.", "An authorized playback request streams the retained recording."],
        ["A1 - Recording is unsupported or too large: reject it and let the student record again.", "A2 - Playback requester lacks access: deny the request without exposing storage details."],
        ["BR-02", "BR-10", "BR-39"],
        ["MSG-RES-05", "MSG-RES-06", "MSG-AUTH-02"],
    ),
    "UC-SPK-02": case(
        "Transcribe and evaluate a Speaking attempt",
        "Resolves authorized attempt recordings, produces a validated transcript, and evaluates the complete performance against six Korean speaking criteria.",
        ["The Speaking attempt is finalized.", "Required private recordings are available and authorized for evaluation."],
        ["A validated transcript and holistic criterion evidence are stored.", "The evaluation remains traceable to the recording set and rubric fingerprint."],
        ["Provider failure produces no fabricated transcript or score.", "Incomplete media remains a truthful failed or unavailable state."],
        ["The orchestrator identifies a Speaking attempt that requires evaluation.", "The media resolver authorizes and loads the retained recordings.", "The transcription provider returns bounded transcript evidence.", "The evaluation provider assesses the complete response against six approved criteria.", "The rule engine validates criterion ranges, overall score and evidence.", "The system stores accepted transcript and evaluation provenance."],
        ["A1 - Recording is missing: stop evaluation and record the missing-media failure.", "A2 - Transcript or evaluation is invalid: reject it and keep scores unavailable."],
        ["BR-07", "BR-40"],
        ["MSG-RES-07", "MSG-RES-08"],
    ),
    "UC-SPK-03": case(
        "Review a holistic Speaking result and per-question evidence",
        "Shows one attempt-level Speaking assessment while allowing the student to inspect authorized recordings, transcripts and question context as evidence.",
        ["A finalized Speaking attempt is visible to the student.", "Phase 13E Speaking evidence presentation has been implemented."],
        ["The overview summarizes the whole performance.", "Detail evidence is available per question without per-question scoring."],
        ["The page does not invent a score for each question.", "Private media remains authorization-protected."],
        ["The student opens Speaking Result Overview.", "The presenter loads the accepted holistic evaluation and six criterion summaries.", "The overview displays overall strengths, weaknesses and next steps.", "The student opens Result Detail for a question.", "The evidence presenter loads authorized recording, transcript and prompt context.", "The page labels these items as evidence and keeps scoring at attempt level."],
        ["A1 - Recording was not retained: show transcript or context that remains available and label media unavailable.", "A2 - Evaluation is pending or failed: show that state without criterion percentages."],
        ["BR-03", "BR-34", "BR-41"],
        ["MSG-RES-08", "MSG-RES-11"],
    ),
    "UC-RES-01": case(
        "View a skill-specific Result Overview",
        "Assembles one authorized attempt result and delegates presentation to an Objective, Writing or Speaking overview designed for that skill.",
        ["The attempt is finalized or has a visible evaluation state.", "The student is authorized to view the attempt."],
        ["A skill-appropriate overview is displayed.", "Scores and statuses come from the exact locked attempt version."],
        ["Incompatible score scales are not combined.", "Opening the overview does not run scoring or AI evaluation."],
        ["The student opens the attempt result route.", "The system authorizes the attempt and loads its locked version identity.", "The result assembler loads objective scores and stored evaluation states.", "The assembler selects the presenter for Reading/Listening, Writing or Speaking.", "The presenter builds skill-specific summary metrics and honest status labels.", "The page renders the overview and available detail action."],
        ["A1 - Evaluation is pending: render pending status and available objective data only.", "A2 - Historical data is incomplete: show an unavailable label rather than a calculated placeholder."],
        ["BR-03", "BR-05", "BR-06", "BR-42"],
        ["MSG-RES-09", "MSG-RES-10"],
    ),
    "UC-RES-02": case(
        "View Result Detail with clearly separated evidence",
        "Builds a question or criterion detail view that separates student input, official content, teacher explanation and AI evidence.",
        ["The student can view the finalized attempt.", "Phase 13E Result Detail presenters have been implemented."],
        ["Authorized evidence is displayed with clear source labels.", "Navigation preserves the exact attempt and immutable question identity."],
        ["Another student's data or unrelated historical content is not exposed.", "Opening detail does not trigger AI generation or mutate evidence."],
        ["The student chooses View details from Result Overview.", "The detail assembler authorizes the attempt and resolves its locked version.", "The assembler loads student answers and skill-specific stored evidence.", "The appropriate Objective, Writing or Speaking presenter builds the view model.", "The page labels each evidence layer and unavailable field.", "The student navigates among questions or criteria within the same attempt."],
        ["A1 - Evidence belongs to another version: deny it and show unavailable state.", "A2 - Optional evidence is missing: keep the remaining result readable and label the missing layer."],
        ["BR-03", "BR-05", "BR-34", "BR-43"],
        ["MSG-RES-11", "MSG-AUTH-02"],
    ),
    "UC-RES-03": case(
        "Handle pending, failed and unavailable result states",
        "Presents honest non-ready states and exposes only recovery actions that the current user is authorized to perform.",
        ["The student can view the attempt result.", "At least one explanation or evaluation is not ready."],
        ["The page identifies pending, failed or unavailable components.", "An authorized retry or re-evaluation can be requested when policy allows."],
        ["Internal provider details are not exposed to the student.", "A recovery request does not erase accepted evidence."],
        ["The result assembler reads durable explanation and evaluation statuses.", "The presenter maps each status to student-safe wording.", "The page shows available scores and evidence without invented replacements.", "If allowed, an authorized user chooses Retry or Re-evaluate.", "The command service checks permission and records the request.", "The refreshed result shows the new durable status."],
        ["A1 - User cannot retry: hide the command and show when or how support can help.", "A2 - Retry is already running: return the existing task state instead of creating a duplicate."],
        ["BR-07", "BR-08", "BR-44"],
        ["MSG-RES-10", "MSG-RES-12"],
    ),
    "UC-PRG-01": case(
        "View real Practice history and summaries",
        "Shows bounded attempt history and summary values calculated from the student's persisted authorized Practice data.",
        ["The student is signed in.", "The progress query can resolve the student identity."],
        ["A bounded history page and truthful summary are displayed.", "Every row links to an authorized attempt when a result is available."],
        ["Placeholder metrics are not shown as real progress.", "Another student's attempts are not included."],
        ["The student opens /practice/progress.", "The controller resolves the authenticated student.", "The service applies pagination and the default date boundary.", "The repository loads authorized attempts and stored result states.", "The service calculates summaries only from compatible available data.", "The page shows history, summary cards and honest empty or error states."],
        ["A1 - No attempts exist: show a useful empty state and a link to the catalog.", "A2 - Part of the data is unavailable: show the available history and a recoverable warning."],
        ["BR-01", "BR-03", "BR-45"],
        ["MSG-PRG-01", "MSG-PRG-02"],
    ),
    "UC-PRG-02": case(
        "Filter and drill down into progress",
        "Applies consistent skill, date and status filters to summaries and history, then opens the exact selected attempt or result.",
        ["The student has Practice history.", "Phase 13F progress query and presentation services have been implemented."],
        ["Summary and history use the same filters.", "Trend information states its sample size and recency."],
        ["Incompatible score scales are not compared.", "A drill-down cannot leave the student's authorized attempt scope."],
        ["The student chooses skill, date or status filters.", "The query service validates and normalizes the filter set.", "The repository loads one bounded compatible dataset.", "The presenter builds summary, trend and history from that same dataset.", "The student selects a history row.", "The system opens the exact authorized attempt result or detail route."],
        ["A1 - Filter has no matching attempts: keep filters visible and show an empty result.", "A2 - Too little comparable data: show sample size and omit the trend claim."],
        ["BR-03", "BR-46", "BR-47"],
        ["MSG-PRG-03", "MSG-PRG-04"],
    ),
    "UC-PRG-03": case(
        "Open authorized recovery actions for incomplete evaluations",
        "Lets a student or operator move from progress to the exact incomplete result and request only the retry or re-evaluation actions allowed by policy.",
        ["An authorized attempt has an incomplete explanation or evaluation.", "Phase 13F recovery presentation has been implemented."],
        ["The student reaches the exact result state.", "An allowed recovery command is recorded without changing accepted evidence."],
        ["Disallowed commands are not shown or executed.", "A server problem is presented as a recoverable state rather than a raw error page."],
        ["The progress page identifies an incomplete durable status.", "The student opens the exact attempt result.", "The recovery presenter explains the state and allowed next action.", "The student or authorized operator chooses the action.", "The command service verifies permission and records the durable transition.", "The page refreshes with the updated student-safe status."],
        ["A1 - No recovery is allowed: provide a support path without exposing internals.", "A2 - Historical test data uses a retired shape: label the compatibility state for Phase 15 cleanup."],
        ["BR-02", "BR-08", "BR-48", "BR-49"],
        ["MSG-PRG-05", "MSG-RES-12"],
    ),
}
