package com.ksh.entities;

public enum PracticeSpeakingMediaCleanupReason {
    TEMPORARY_EXPIRY,
    SUPERSEDED_RETENTION,
    LOGICAL_DELETE,
    DISCARD_ATTEMPT,
    ACTIVATION_COMPENSATION,
    MIGRATION_SOURCE_DELETE,
    CONSENT_WITHDRAWAL
}
