CREATE TABLE practice_speaking_media (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    storage_provider VARCHAR(32) NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    mime_type VARCHAR(128) NOT NULL,
    container VARCHAR(32) NOT NULL,
    codec VARCHAR(64) NOT NULL,
    byte_size BIGINT NOT NULL,
    duration_ms BIGINT NOT NULL,
    content_hash CHAR(64) NOT NULL,
    status VARCHAR(30) NOT NULL,
    lock_version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    CONSTRAINT uk_psm_storage UNIQUE (storage_provider, storage_key),
    INDEX idx_psm_attempt_question_status (attempt_id, question_id, status),
    INDEX idx_psm_attempt_status (attempt_id, status),
    CONSTRAINT fk_psm_attempt FOREIGN KEY (attempt_id) REFERENCES practice_attempts(id),
    CONSTRAINT fk_psm_question FOREIGN KEY (question_id) REFERENCES practice_questions(id),
    CONSTRAINT chk_psm_storage_provider CHECK (storage_provider IN ('LOCAL','OBJECT_STORAGE')),
    CONSTRAINT chk_psm_status CHECK (status IN ('READY','SUPERSEDED','DELETED')),
    CONSTRAINT chk_psm_byte_size CHECK (byte_size > 0),
    CONSTRAINT chk_psm_duration_ms CHECK (duration_ms > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
